name: $(packageVersion)$(rev:.r)
pool:
  vmImage: windows-2019
trigger: none
steps:
  - task: PowerShell@2
    displayName: 'Run Default Cake target via bootstrapper'
    inputs:
      targetType: filePath
      filePath: ./build.ps1
      arguments: '-Target Default -Verbosity Quiet'
  - task: VSTest@2
    displayName: 'Test Assemblies'
    inputs:
      testAssemblyVer2: |
        **\*Tests.Unit*.dll
        !**\*TestAdapter.dll
        !**\obj\**
      codeCoverageEnabled: true
variables:
  - group: Development Hub
