name: $(solution) - $(commitMessage) - $(triggeredBy)
pool:
  vmImage: windows-latest
trigger: none
steps:
  - checkout: self
    persistCredentials: true
  - powershell: >-
      $env:GIT_REDIRECT_STDERR = '2>&1';
      git config --global user.email $env:TRIGGEREDBYEMAIL;
      git config --global user.name $env:TRIGGEREDBY;
      git checkout master;
      if ($env:SOURCEBRANCH)
      {
        git merge origin/$env:SOURCEBRANCH --no-commit;
      }
      Invoke-Expression "&$(Build.SourcesDirectory)\build.ps1 -Target ExtractSolutionFromDevelopmentHub -ScriptArgs `"--solution=$env:SOLUTION`",`"--unmanagedNoteId=$env:UNMANAGEDNOTEID`",`"--managedNoteId=$env:MANAGEDNOTEDID`" -Verbosity Diagnostic";
      git add .;
      git reset -- NuGet.config;
      $commitMessage = $env:COMMITMESSAGE;
      if ($env:WORKITEMID) 
      {
        $commitMessage += " #$env:WORKITEMID";
      }
      git commit -m $commitMessage;
      git push origin;
    displayName: Extract and commit solution
    env:
      CAKE_DYNAMICS_PASSWORD: $(dynamicsPassword)
      CAKE_DYNAMICS_USERNAME: $(dynamicsUsername)
variables:
  - name: workItemId
    value: ""